### ISSUE TITLE
Go there link points to incorrect URL

### ISSUE THREAD

**Issue by jelmstrom** [marcusoftnet/page-logger#1]
Should point to monitored site URL, instead of https://page-logger

**Comment by jelmstrom** [comment]
<a target="_blank" href="/2014/01/share-your-internet-connection-via-wifi.html" class="btn btn-default btn-sm">Go there!</a>

:)

**Comment by marcusoftnet** [comment]
Fixed! In commit: https://github.com/marcusoftnet/page-logger/commit/3e9b4fdf0f49cf7dc8b38888f62b26a5ab76b607 

So basically I just output the URL that is posted. Tried to be smart first... but this was simpler. 

Thanks
